Develop
datakind/Data-Observation-Toolkit pull request #83
Opened 2023-03-17 00:34 UTC by JanPeterDatakind

Tidied up our PRs dating back to December 2022

2023-03-21 23:22 UTC, dividor requested changes
Fantastic Jan, thanks SOOOOOO much!! Huge amount of work. Please could you add some comments to the PR to indicate you've done testing of the UI, thanks.

One minor change on linting being reverted.

@lrnzcig, any suggestions? Would love your thoughts!

This is a suite of fixes that came in from field testing. Once done we aim to refactor some of the code to simplify, add the last dot_config.yml to be in the DB as it confuses everyone, then move onto more validation of entities and tests.

2023-03-21 23:22 UTC, dividor commented on docker/airflow/dags/run_dot_project.py
Actually @JanPeterDatakind, I fear we may have reverted @lrnzcig linting of this file. Could you please revert the formatting to as it was before. The easiest way is to run lint.py, see CONTRIBUTION.md for instructions. Thanks!

2023-03-22 19:05 UTC, JanPeterDatakind commented on docker/airflow/dags/run_dot_project.py
Rolled back the changes as requested  :)

2023-03-27 20:29 UTC, dividor approved these changes

2023-03-27 20:31 UTC, merged